from spack import *


class Remi(CMakePackage):
    """REMI is a Mochi microservice designed to handle the migration of sets of files
    from a node to another. It uses RDMA and memory mapping to efficiently transfer
    potentially large groups of files at once."""

    homepage = "https://xgitlab.cels.anl.gov/sds/remi"
    url = "https://xgitlab.cels.anl.gov/sds/remi"
    git='https://xgitlab.cels.anl.gov/sds/remi.git'

    version('develop', branch='master')
    version('0.2.1', tag='v0.2.1')
    version('0.2', tag='v0.2')
    version('0.1.1', tag='v0.1.1')
    version('0.1', tag='v0.1')

    variant('cxx11abi', default=True,
                        description='Use CXX11 ABI for the symbols generated by GCC')

    depends_on('thallium+cxx11abi@0.3:', when='+cxx11abi')
    depends_on('thallium~cxx11abi@0.3:', when='~cxx11abi')
    depends_on('libuuid')
    depends_on('abt-io@0.1:')

    patch('0001-explicitly-request-C-14.patch')


    def cmake_args(self):
        args = ["-DBUILD_SHARED_LIBS:BOOL=ON" ]
        if(not self.spec.variants['cxx11abi'].value):
            args.extend(['-DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0 -D_GLIBCXX_USE_CXX14_ABI=0'])
        return args
