from spack import *

class Thallium(CMakePackage):
    """Thallium is a C++14 library wrapping Margo, Mercury,
    and Argobots and providing an object-oriented way to use these libraries."""

    homepage = "https://xgitlab.cels.anl.gov/sds/thallium"
    url = "https://xgitlab.cels.anl.gov/sds/thallium"
    git = "https://xgitlab.cels.anl.gov/sds/thallium.git"

    version('develop', branch='master')
    version('0.3.4', tag='v0.3.4')
    version('0.3.3', tag='v0.3.3')
    version('0.3.2', tag='v0.3.2')
    version('0.3.1', tag='v0.3.1')
    version('0.3', tag='v0.3')

    depends_on('margo@0.4:')
    # thallium relies on std::decay_t
    conflicts('%gcc@:4.9.0');

    variant('cxx11abi', default=True,
            description='Use CXX11 ABI for the symbols generated by GCC')

    def cmake_args(self):
        args = ["-DBUILD_SHARED_LIBS:BOOL=ON" ]
        if(not self.spec.variants['cxx11abi'].value):
            args.extend(['-DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0 -D_GLIBCXX_USE_CXX14_ABI=0'])
        return args
